"""Reader for Source 1 studio models (.mdl, versions 44-49).

Layouts follow the public studio.h structures of the Source SDK. Only reading is done here;
the structures are documented in docs/formats.md. Unknown or unsupported parts are kept as
raw byte ranges on the model so nothing is silently dropped from an archive.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from .binary import FormatError, Reader

MDL_MAGIC = b"IDST"
SUPPORTED_VERSIONS = range(44, 50)

HEADER_SIZE = 408
BONE_SIZE = 216
ATTACHMENT_SIZE = 92
HITBOXSET_SIZE = 12
HITBOX_SIZE = 68
TEXTURE_SIZE = 64
BODYPART_SIZE = 16
MODEL_SIZE = 148
MESH_SIZE = 116
FLEXDESC_SIZE = 4
FLEXCONTROLLER_SIZE = 20
FLEX_SIZE = 60
POSEPARAM_SIZE = 20
INCLUDEMODEL_SIZE = 8
SEQDESC_SIZE = 212
ANIMDESC_SIZE = 100
EYEBALL_SIZE = 172

STUDIO_FLAG_NAMES = {
    0x1: "autogenerated_hitbox",
    0x2: "used_bone_merge",
    0x4: "translucent_twopass",
    0x10: "static_prop",
    0x20: "has_shadowlod",
    0x40: "use_shadowlod_materials",
    0x80: "obsolete",
    0x200: "no_forced_fade",
    0x800: "force_phoneme_crossfade",
    0x1000: "constant_directional_light_dot",
    0x2000: "flexes_converted",
    0x4000: "built_in_preview_mode",
    0x8000: "ambient_boost",
    0x10000: "do_not_cast_shadows",
    0x20000: "cast_texture_shadows",
    0x80000: "vert_anim_fixed_point_scale",
}


@dataclass
class Bone:
    index: int
    name: str
    parent: int
    pos: tuple[float, float, float]
    quat: tuple[float, float, float, float]
    rot: tuple[float, float, float]
    pos_scale: tuple[float, float, float]
    rot_scale: tuple[float, float, float]
    pose_to_bone: tuple[float, ...]  # 3x4 row-major
    flags: int
    proc_type: int
    physics_bone: int
    surface_prop: str
    contents: int


@dataclass
class Attachment:
    name: str
    flags: int
    bone: int
    local: tuple[float, ...]  # 3x4 row-major


@dataclass
class Hitbox:
    bone: int
    group: int
    bbmin: tuple[float, float, float]
    bbmax: tuple[float, float, float]
    name: str


@dataclass
class HitboxSet:
    name: str
    hitboxes: list[Hitbox]


@dataclass
class Flex:
    flexdesc: int
    targets: tuple[float, float, float, float]
    num_verts: int
    vert_offset: int  # absolute file offset of the vertex animation array
    flexpair: int
    vertanim_type: int  # 0 = normal, 1 = wrinkle


@dataclass
class Mesh:
    material: int
    num_vertices: int
    vertex_offset: int
    mesh_id: int
    center: tuple[float, float, float]
    lod_vertex_counts: tuple[int, ...]
    flexes: list[Flex] = field(default_factory=list)


@dataclass
class SubModel:
    name: str
    bounding_radius: float
    num_vertices: int
    vertex_index: int  # byte offset into the VVD vertex stream (divide by 48 for the vertex index)
    num_eyeballs: int
    meshes: list[Mesh]


@dataclass
class BodyPart:
    name: str
    base: int
    models: list[SubModel]


@dataclass
class FlexController:
    type: str
    name: str
    min: float
    max: float


@dataclass
class PoseParameter:
    name: str
    flags: int
    start: float
    end: float
    loop: float


@dataclass
class AnimDesc:
    index: int
    name: str
    fps: float
    flags: int
    num_frames: int
    anim_block: int
    anim_offset: int  # absolute offset of the first mstudioanim_t when stored in the .mdl
    section_frames: int
    section_offset: int
    num_movements: int
    num_ik_rules: int


@dataclass
class Sequence:
    index: int
    label: str
    activity: str
    flags: int
    activity_weight: int
    num_events: int
    bbmin: tuple[float, float, float]
    bbmax: tuple[float, float, float]
    group_size: tuple[int, int]
    param_index: tuple[int, int]
    anim_indices: list[int]
    fade_in: float
    fade_out: float
    keyvalues: str


@dataclass
class StudioModel:
    version: int
    checksum: int
    name: str
    length: int
    eye_position: tuple[float, float, float]
    illum_position: tuple[float, float, float]
    hull_min: tuple[float, float, float]
    hull_max: tuple[float, float, float]
    view_bbmin: tuple[float, float, float]
    view_bbmax: tuple[float, float, float]
    flags: int
    mass: float
    contents: int
    surface_prop: str
    keyvalues: str
    bones: list[Bone]
    attachments: list[Attachment]
    hitbox_sets: list[HitboxSet]
    textures: list[str]
    cd_textures: list[str]
    skin_families: list[list[int]]
    body_parts: list[BodyPart]
    flex_descs: list[str]
    flex_controllers: list[FlexController]
    pose_parameters: list[PoseParameter]
    include_models: list[str]
    anim_descs: list[AnimDesc]
    sequences: list[Sequence]
    anim_block_name: str
    num_anim_blocks: int
    anim_blocks: list[tuple[int, int]]
    num_bone_controllers: int
    num_ik_chains: int
    num_flex_rules: int
    vert_anim_fixed_point_scale: float
    unsupported: list[str] = field(default_factory=list)

    @property
    def flag_names(self) -> list[str]:
        return [name for bit, name in STUDIO_FLAG_NAMES.items() if self.flags & bit]

    @property
    def is_static_prop(self) -> bool:
        return bool(self.flags & 0x10)

    def material_paths(self) -> list[str]:
        """All candidate material paths (cdmaterials x texture names), in lookup order."""
        out = []
        for tex in self.textures:
            for cd in self.cd_textures or [""]:
                out.append(_join_material(cd, tex))
        return out


def _join_material(cd: str, tex: str) -> str:
    cd = cd.replace("\\", "/").strip("/")
    tex = tex.replace("\\", "/").lstrip("/")
    return f"{cd}/{tex}".lower() if cd else tex.lower()


def _mat34(r: Reader, off: int) -> tuple[float, ...]:
    return r.unpack("12f", off)


def _array(count: int, what: str, limit: int = 1_000_000) -> int:
    if count < 0 or count > limit:
        raise FormatError(f"mdl: implausible {what} count {count}")
    return count


def read_mdl(data: bytes) -> StudioModel:
    r = Reader(data, "mdl")
    if len(data) < HEADER_SIZE or data[:4] != MDL_MAGIC:
        raise FormatError("mdl: missing IDST header; not a Source 1 studio model")
    (version, checksum) = r.unpack("ii", 4)
    if version not in SUPPORTED_VERSIONS:
        raise FormatError(f"mdl: version {version} is not supported (supported: 44-49)")
    name = r.fixed_str(12, 64)
    length = r.i32(76)
    if length != len(data):
        raise FormatError(f"mdl: header length {length} does not match file size {len(data)}")

    h = r.unpack("i" * 64, 152)  # flags .. fields up to localposeparamindex region, see _H below
    idx = dict(zip(_H, h, strict=False))

    bones = _read_bones(r, idx["numbones"], idx["boneindex"])
    attachments = _read_attachments(r, idx["numlocalattachments"], idx["localattachmentindex"])
    hitbox_sets = _read_hitbox_sets(r, idx["numhitboxsets"], idx["hitboxsetindex"])
    textures = [
        r.rel_str(idx["textureindex"] + i * TEXTURE_SIZE, r.i32(idx["textureindex"] + i * TEXTURE_SIZE))
        for i in range(_array(idx["numtextures"], "texture"))
    ]
    cd_textures = [
        r.cstr(r.i32(idx["cdtextureindex"] + i * 4)) for i in range(_array(idx["numcdtextures"], "cdtexture"))
    ]
    skin_families = []
    nref, nfam = idx["numskinref"], idx["numskinfamilies"]
    for f in range(_array(nfam, "skin family", 10_000)):
        skin_families.append(list(r.unpack(f"{nref}h", idx["skinindex"] + f * nref * 2)) if nref else [])

    body_parts = _read_body_parts(r, idx["numbodyparts"], idx["bodypartindex"])
    flex_descs = [
        r.rel_str(idx["flexdescindex"] + i * FLEXDESC_SIZE, r.i32(idx["flexdescindex"] + i * FLEXDESC_SIZE))
        for i in range(_array(idx["numflexdesc"], "flexdesc"))
    ]
    flex_controllers = []
    for i in range(_array(idx["numflexcontrollers"], "flexcontroller")):
        o = idx["flexcontrollerindex"] + i * FLEXCONTROLLER_SIZE
        t, n, _l2g, mn, mx = r.unpack("iiiff", o)
        flex_controllers.append(FlexController(r.rel_str(o, t), r.rel_str(o, n), mn, mx))

    (
        numposeparams,
        poseparamindex,
        surfacepropindex,
        keyvalueindex,
        keyvaluesize,
        _nikl,
        _ikli,
    ) = r.unpack("7i", 300)
    mass = r.f32(328)
    (
        contents,
        numincludemodels,
        includemodelindex,
        _vm,
        szanimblocknameindex,
        numanimblocks,
        animblockindex,
    ) = r.unpack("7i", 332)
    vert_anim_scale = r.f32(392)
    studiohdr2index = r.i32(400)

    pose_parameters = []
    for i in range(_array(numposeparams, "pose parameter")):
        o = poseparamindex + i * POSEPARAM_SIZE
        n, fl, st, en, lp = r.unpack("iifff", o)
        pose_parameters.append(PoseParameter(r.rel_str(o, n), fl, st, en, lp))

    include_models = []
    for i in range(_array(numincludemodels, "include model")):
        o = includemodelindex + i * INCLUDEMODEL_SIZE
        _label, fname = r.unpack("ii", o)
        include_models.append(r.rel_str(o, fname))

    anim_blocks = []
    for i in range(_array(numanimblocks, "anim block")):
        anim_blocks.append(r.unpack("ii", animblockindex + i * 8))

    anim_descs = _read_anim_descs(r, idx["numlocalanim"], idx["localanimindex"])
    sequences = _read_sequences(r, idx["numlocalseq"], idx["localseqindex"])

    surface_prop = r.cstr(surfacepropindex) if surfacepropindex else ""
    keyvalues = (
        r.raw(keyvalueindex, keyvaluesize).split(b"\0", 1)[0].decode("utf-8", "replace")
        if (keyvaluesize > 0)
        else ""
    )
    if studiohdr2index:
        # studiohdr2_t may carry a long model name.
        long_name_rel = r.i32(studiohdr2index + 20)
        if long_name_rel:
            name = r.cstr(studiohdr2index + long_name_rel)

    unsupported = []
    if idx["numlocalnodes"]:
        unsupported.append("sequence transition nodes (kept in original file only)")
    if idx["numikchains"]:
        unsupported.append("IK chains (kept in original file only)")
    if idx["numflexrules"]:
        unsupported.append("flex rules (kept in original file only)")
    if idx["nummouths"]:
        unsupported.append("mouths (kept in original file only)")

    return StudioModel(
        version=version,
        checksum=checksum,
        name=name,
        length=length,
        eye_position=r.vec3(80),
        illum_position=r.vec3(92),
        hull_min=r.vec3(104),
        hull_max=r.vec3(116),
        view_bbmin=r.vec3(128),
        view_bbmax=r.vec3(140),
        flags=idx["flags"],
        mass=mass,
        contents=contents,
        surface_prop=surface_prop,
        keyvalues=keyvalues,
        bones=bones,
        attachments=attachments,
        hitbox_sets=hitbox_sets,
        textures=textures,
        cd_textures=cd_textures,
        skin_families=skin_families,
        body_parts=body_parts,
        flex_descs=flex_descs,
        flex_controllers=flex_controllers,
        pose_parameters=pose_parameters,
        include_models=include_models,
        anim_descs=anim_descs,
        sequences=sequences,
        anim_block_name=r.cstr(szanimblocknameindex) if szanimblocknameindex else "",
        num_anim_blocks=numanimblocks,
        anim_blocks=anim_blocks,
        num_bone_controllers=idx["numbonecontrollers"],
        num_ik_chains=idx["numikchains"],
        num_flex_rules=idx["numflexrules"],
        vert_anim_fixed_point_scale=vert_anim_scale if idx["flags"] & 0x80000 else 1.0 / 4096.0,
        unsupported=unsupported,
    )


# Integer header fields starting at offset 152 (flags), in file order.
_H = [
    "flags", "numbones", "boneindex", "numbonecontrollers", "bonecontrollerindex", "numhitboxsets",
    "hitboxsetindex", "numlocalanim", "localanimindex", "numlocalseq", "localseqindex",
    "activitylistversion", "eventsindexed", "numtextures", "textureindex", "numcdtextures",
    "cdtextureindex", "numskinref", "numskinfamilies", "skinindex", "numbodyparts", "bodypartindex",
    "numlocalattachments", "localattachmentindex", "numlocalnodes", "localnodeindex",
    "localnodenameindex", "numflexdesc", "flexdescindex", "numflexcontrollers", "flexcontrollerindex",
    "numflexrules", "flexruleindex", "numikchains", "ikchainindex", "nummouths", "mouthindex",
]  # fmt: skip


def _read_bones(r: Reader, count: int, base: int) -> list[Bone]:
    bones = []
    for i in range(_array(count, "bone", 256)):
        o = base + i * BONE_SIZE
        name_rel, parent = r.unpack("ii", o)
        flags, proctype, _procindex, physicsbone, surfprop_rel, contents = r.unpack("6i", o + 160)
        bones.append(
            Bone(
                index=i,
                name=r.rel_str(o, name_rel),
                parent=parent,
                pos=r.vec3(o + 32),
                quat=r.unpack("4f", o + 44),
                rot=r.vec3(o + 60),
                pos_scale=r.vec3(o + 72),
                rot_scale=r.vec3(o + 84),
                pose_to_bone=_mat34(r, o + 96),
                flags=flags,
                proc_type=proctype,
                physics_bone=physicsbone,
                surface_prop=r.rel_str(o, surfprop_rel),
                contents=contents,
            )
        )
        if parent >= i or parent < -1:
            raise FormatError(f"mdl: bone {i} has invalid parent {parent}")
    return bones


def _read_attachments(r: Reader, count: int, base: int) -> list[Attachment]:
    out = []
    for i in range(_array(count, "attachment")):
        o = base + i * ATTACHMENT_SIZE
        name_rel, flags, bone = r.unpack("iIi", o)
        out.append(Attachment(r.rel_str(o, name_rel), flags, bone, _mat34(r, o + 12)))
    return out


def _read_hitbox_sets(r: Reader, count: int, base: int) -> list[HitboxSet]:
    sets = []
    for i in range(_array(count, "hitbox set")):
        o = base + i * HITBOXSET_SIZE
        name_rel, num, hb_rel = r.unpack("iii", o)
        boxes = []
        for j in range(_array(num, "hitbox")):
            b = o + hb_rel + j * HITBOX_SIZE
            bone, group = r.unpack("ii", b)
            boxes.append(Hitbox(bone, group, r.vec3(b + 8), r.vec3(b + 20), r.rel_str(b, r.i32(b + 32))))
        sets.append(HitboxSet(r.rel_str(o, name_rel), boxes))
    return sets


def _read_body_parts(r: Reader, count: int, base: int) -> list[BodyPart]:
    parts = []
    for i in range(_array(count, "bodypart")):
        o = base + i * BODYPART_SIZE
        name_rel, nummodels, pbase, model_rel = r.unpack("iiii", o)
        models = []
        for j in range(_array(nummodels, "model")):
            m = o + model_rel + j * MODEL_SIZE
            mname = r.fixed_str(m, 64)
            _type, radius, nummeshes, mesh_rel, numverts, vertindex, _tan = r.unpack("ifiiiii", m + 64)
            _natt, _atti, numeyeballs, _eyei = r.unpack("iiii", m + 92)
            meshes = []
            for k in range(_array(nummeshes, "mesh")):
                me = m + mesh_rel + k * MESH_SIZE
                material, _midx, mverts, voff, numflexes, flex_rel, _mt, _mp, meshid = r.unpack("9i", me)
                flexes = []
                for f in range(_array(numflexes, "flex")):
                    fo = me + flex_rel + f * FLEX_SIZE
                    fd, t0, t1, t2, t3, nv, vrel, pair = r.unpack("iffffiii", fo)
                    vtype = r.u8(fo + 32)
                    flexes.append(Flex(fd, (t0, t1, t2, t3), nv, fo + vrel, pair, vtype))
                meshes.append(
                    Mesh(
                        material=material,
                        num_vertices=mverts,
                        vertex_offset=voff,
                        mesh_id=meshid,
                        center=r.vec3(me + 36),
                        lod_vertex_counts=r.unpack("8i", me + 52),
                        flexes=flexes,
                    )
                )
            models.append(SubModel(mname, radius, numverts, vertindex, numeyeballs, meshes))
        parts.append(BodyPart(r.rel_str(o, name_rel), pbase, models))
    return parts


def _read_anim_descs(r: Reader, count: int, base: int) -> list[AnimDesc]:
    out = []
    for i in range(_array(count, "animation")):
        o = base + i * ANIMDESC_SIZE
        _baseptr, name_rel, fps, flags, numframes, nummovements, _movi = r.unpack("iifiiii", o)
        animblock, animindex, numikrules = r.unpack("iii", o + 52)
        sectionindex, sectionframes = r.unpack("ii", o + 80)
        out.append(
            AnimDesc(
                index=i,
                name=r.rel_str(o, name_rel),
                fps=fps,
                flags=flags,
                num_frames=numframes,
                anim_block=animblock,
                anim_offset=o + animindex if animblock == 0 else animindex,
                section_frames=sectionframes,
                section_offset=o + sectionindex if sectionindex else 0,
                num_movements=nummovements,
                num_ik_rules=numikrules,
            )
        )
    return out


def _read_sequences(r: Reader, count: int, base: int) -> list[Sequence]:
    out = []
    for i in range(_array(count, "sequence")):
        o = base + i * SEQDESC_SIZE
        _bp, label_rel, act_rel, flags, _act, actweight, numevents, _evi = r.unpack("8i", o)
        numblends, animindexindex, _movi, gs0, gs1, pi0, pi1 = r.unpack("7i", o + 56)
        fade_in, fade_out = r.unpack("ff", o + 104)
        kv_index, kv_size = r.unpack("ii", o + 172)
        n = max(gs0, 1) * max(gs1, 1)
        anims = list(r.unpack(f"{n}h", o + animindexindex)) if n and animindexindex else []
        kv = r.raw(o + kv_index, kv_size).split(b"\0", 1)[0].decode("utf-8", "replace") if kv_size else ""
        out.append(
            Sequence(
                index=i,
                label=r.rel_str(o, label_rel),
                activity=r.rel_str(o, act_rel),
                flags=flags,
                activity_weight=actweight,
                num_events=numevents,
                bbmin=r.vec3(o + 32),
                bbmax=r.vec3(o + 44),
                group_size=(gs0, gs1),
                param_index=(pi0, pi1),
                anim_indices=anims,
                fade_in=fade_in,
                fade_out=fade_out,
                keyvalues=kv,
            )
        )
        del numblends
    return out
