// <auto-generated> by tools/prepare_sbox_project.py from the AssetDocuments. Do not edit.
namespace SourceBridge.Tests;

public static class GeneratedCases
{
	public static readonly IReadOnlyList<PropTest.Case> Props = new PropTest.Case[]
	{
		new( "s1/prefabs/models/sourcebridge/crate.prefab", 40.000f, 2 ),
	};
}
