"""Convert the fixture content into the s&box target-test project (sbox/).

    python tools/prepare_sbox_project.py

1. runs the SourceBridge import for every fixture model into sbox/Assets/s1/...
2. writes sbox/Code/SourceBridge/GeneratedCases.cs with the expectations the in-engine tests check
   (values come from the AssetDocuments, i.e. from the original Source 1 files)
3. writes sbox/Assets/scenes/sourcebridge_tests.scene, derived from Facepunch's game.minimal scene
   (templates/sbox/reference/minimal.scene) with the sample cubes replaced by the test runner

The output is deterministic; tests/test_sbox_project.py fails if the committed project is stale.
"""

from __future__ import annotations

import copy
import json
import sys
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from sourcebridge.pipeline import import_model, import_vehicle  # noqa: E402
from sourcebridge.sources import GmaSource, Mount  # noqa: E402

SBOX = ROOT / "sbox"
GMA = ROOT / "fixtures" / "build" / "sourcebridge_fixtures.gma"
MODELS = ["models/sourcebridge/crate.mdl", "models/sourcebridge/mannequin.mdl"]
VEHICLES = ["sb_buggy"]
GROUND_SCALE = 120  # the template plane is 500x500; the drive test needs room


def guid(seed: str) -> str:
    return str(uuid.uuid5(uuid.NAMESPACE_URL, "sourcebridge-scene:" + seed))


def convert(project: Path) -> list[dict]:
    docs = []
    for model in MODELS:
        docs.append(import_model(Mount([GmaSource(GMA)]), model, project, SBOX / "Assets"))
    for vid in VEHICLES:
        docs.append(import_vehicle(Mount([GmaSource(GMA)]), vid, project, SBOX / "Assets"))
    return docs


def cases_cs(docs: list[dict]) -> str:
    lines = [
        "// <auto-generated> by tools/prepare_sbox_project.py from the AssetDocuments. Do not edit.",
        "namespace SourceBridge.Tests;",
        "",
        "public static class GeneratedCases",
        "{",
        "\tpublic static readonly IReadOnlyList<PropTest.Case> Props = new PropTest.Case[]",
        "\t{",
    ]
    for d in docs:
        if d.get("kind") != "prop":
            continue
        mass = (d.get("physics") or {}).get("total_mass") or 0
        groups = max(1, len(d["model"]["skin_families"]))
        prefab = d["outputs"]["prefab"]
        lines.append(f'\t\tnew( "{prefab}", {float(mass):.3f}f, {groups} ),')
    lines += ["\t};", ""]
    lines += [
        "\tpublic static readonly IReadOnlyList<CharacterTest.Case> Characters = new CharacterTest.Case[]",
        "\t{",
    ]
    for d in docs:
        if d.get("kind") != "character":
            continue
        o = d["outputs"]
        m = d["model"]
        seqs = ", ".join(f'"{s["name"]}"' for s in o["sequences"])
        atts = ", ".join(f'"{a["name"]}"' for a in m["attachments"])
        bodygroups = sum(1 for bp in m["body_parts"] if len(bp["models"]) > 1)
        phys = d.get("physics") or {"solids": [], "text_blocks": []}
        parts = len(phys["solids"])
        joints = sum(1 for b in phys["text_blocks"] if b["kind"] == "ragdollconstraint")
        ragdoll = f'"{o["ragdoll_prefab"]}"' if o.get("ragdoll_prefab") else "null"
        lines.append(f'\t\tnew( "{o["prefab"]}", {ragdoll}, {len(m["bones"])},')
        lines.append(f"\t\t\tnew[] {{ {seqs} }}, new[] {{ {atts} }}, {bodygroups}, {parts}, {joints},")
        lines.append("\t\t\tnew CharacterTest.SequenceCheck[]")
        lines.append("\t\t\t{")
        for c in o["sequence_checks"]:
            bones = ", ".join(
                f'new( "{b}", new Vector3( {p[0]:.4f}f, {p[1]:.4f}f, {p[2]:.4f}f ) )'
                for b, p in c["bones"].items()
            )
            lines.append(
                f'\t\t\t\tnew( "{c["sequence"]}", {c["frame"]}, {c["time"]:.6f}f, new CharacterTest.BoneExpectation[] {{ {bones} }} ),'
            )
        lines.append("\t\t\t} ),")
    lines += ["\t};", ""]
    lines += [
        "\tpublic static readonly IReadOnlyList<VehicleTest.Case> Vehicles = new VehicleTest.Case[]",
        "\t{",
    ]
    for d in docs:
        v = d.get("vehicle")
        if not v:
            continue
        mass = v["body"]["mass"]["value"] or (d.get("physics") or {}).get("total_mass") or 0
        lines.append(
            f'\t\tnew( "{d["outputs"]["extra"]["vehicle_prefab"]}", {float(mass):.1f}f, '
            f"{v['engine']['max_speed']['value']:.1f}f, {v['engine']['max_reverse_speed']['value']:.1f}f, "
            f"{v['track_width']['value']:.1f}f ),"
        )
    lines += ["\t};", "}", ""]
    return "\n".join(lines)


def scene() -> str:
    tpl = json.loads((ROOT / "templates/sbox/reference/minimal.scene").read_text())
    s = copy.deepcopy(tpl)
    s["GameObjects"] = [g for g in s["GameObjects"] if not g.get("Name", "").startswith("Cube")]
    for g in s["GameObjects"]:
        if g.get("Name") == "Plane":
            g["Scale"] = f"{GROUND_SCALE},{GROUND_SCALE},{GROUND_SCALE}"
    s["__guid"] = guid("scene")
    runner = copy.deepcopy(next(g for g in tpl["GameObjects"] if g.get("Name") == "Plane"))
    runner.update(
        {
            "__guid": guid("runner"),
            "Name": "SourceBridge Tests",
            "Position": "0,0,0",
            "Rotation": "0,0,0,1",
            "Scale": "1,1,1",
            "Components": [
                {
                    "__type": "SourceBridge.Tests.PropTest",
                    "__guid": guid("proptest"),
                    "__enabled": True,
                    "Flags": 0,
                    "DropHeight": 96,
                    "GroundTolerance": 1.5,
                    "Timeout": 10,
                },
                {
                    "__type": "SourceBridge.Tests.CharacterTest",
                    "__guid": guid("charactertest"),
                    "__enabled": True,
                    "Flags": 0,
                    "PositionTolerance": 1.0,
                    "GroundTolerance": 3.0,
                    "RagdollTimeout": 10,
                },
                {
                    "__type": "SourceBridge.Tests.VehicleTest",
                    "__guid": guid("vehicletest"),
                    "__enabled": True,
                    "Flags": 0,
                    "WheelTolerance": 1.5,
                },
            ],
            "Children": [],
        }
    )
    s["GameObjects"].append(runner)
    s["Title"] = "SourceBridge target tests"
    s["Description"] = "Spawns converted Source 1 content and logs SOURCEBRIDGE-TEST PASS/FAIL lines."
    return json.dumps(s, indent=2) + "\n"


def main() -> None:
    import tempfile

    with tempfile.TemporaryDirectory() as tmp:
        docs = convert(Path(tmp))
    for d in docs:
        if d["status"]["progress"] != "converted":
            raise SystemExit(f"{d['source_path']}: {d['status']}")
    (SBOX / "Code/SourceBridge/GeneratedCases.cs").write_text(cases_cs(docs))
    (SBOX / "Assets/scenes/sourcebridge_tests.scene").write_text(scene())
    print(f"prepared {len(docs)} model(s) in {SBOX}")


if __name__ == "__main__":
    main()
